### PR TITLE
Async/await for api calls

### PR DESCRIPTION
**Pull request by marko911**
In order to move away from using etools-ajax and having to put 10 elements like this: 
```
<etools-ajax-sp
                id="tpmPartners"
                url="[[partnersUrl]]"
                on-success="_partnersLoaded"
                on-fail="_partnersError">
        </etools-ajax-sp>

        <etools-ajax-sp
                method="OPTIONS"
                url="[[partnersOptionsUrl]]"
                on-success="_handlePartnersOptions"
                on-fail="_handlePartnersOptions">
        </etools-ajax-sp>

        <etools-ajax-sp
                method="OPTIONS"
                url="[[visitsOptionsUrl]]"
                on-success="_handleVisitsOptions"
                on-fail="_handleVisitsOptions">
        </etools-ajax-sp>

        <!--partner organisations-->
        <etools-ajax-sp
                endpoint="[[organisationsEndpoint]]"
                caching-storage="custom"
                dexie-db-collection="partners"
                on-success="_organisationsLoaded"
                on-fail="_organisationsError">
        </etools-ajax-sp>

        <!-- filter TP-->
        <etools-ajax-sp
                url="[[filterIPUrl]]"
                on-success="_filterIPLoaded"
                on-fail="_filterIPError">
        </etools-ajax-sp>

        <!-- filter Sections-->
        <etools-ajax-sp
                url="[[filterSectionsUrl]]"
                on-success="_filterSectionsLoaded"
                on-fail="_filterSectionsError">
        </etools-ajax-sp>

        <!-- filter CP Outputs-->
        <etools-ajax-sp
                url="[[filterCpOutputsUrl]]"
                on-success="_filterOutputsLoaded"
                on-fail="_filterOutputsError">
        </etools-ajax-sp>

        <!--Sections Covered-->
        <etools-ajax-sp
                url="[[sectionsEndpoint]]"
                on-success="_sectionsLoaded"
                on-fail="_sectionsError">
        </etools-ajax-sp>

        <!--Unicef Users-->
        <etools-ajax-sp
                url="[[unicefUsersEndpoint]]"
                on-success="_unicefUsersLoaded"
                on-fail="_unicefUsersError">
        </etools-ajax-sp>
```

I suggest we just use `babel-preset-env` and then a `Promise.all([...async functions])`.
I do know that it is probably not your concern anymore for this module but this pattern can be useful for future modules you work on. 
We can use properties in polymer to configure each endpoint options ie method, body etc.
Let me know your thoughts @v-urbanovich

### CODE REVIEW

**Comment by v-urbanovich** [comment]
Yes, I agree with this concept. Can you make this changes?

**Comment by marko911** [comment]
I will need to make a wrapper so we can use dexie caching as an option. Etools-ajax for polymer 2 has these functions already so maybe I will just copy that. Will let you know ...

**Comment by robertavram** [comment]
@marko911 can you check what has been built in to the latest etools-ajax version, maybe check how PMP is doing this... we can't have multiple ways of doing the same thing... if this is something that hasn;t been addressed then we have to make sure that everyone's aware of the approach...  refactoring should be last on our list of priorities unless impacting any ticket we're working on.

**Comment by robertavram** [comment]
@adi130987 can you weigh in?

**Comment by marko911** [comment]
Dont worry I will not implement this, I didn't realize etools-ajax had this done for polymer 1...its all good

**Comment by adi130987** [comment]
Yes, Polymer 1 version of etools-ajax has everything you need for dexiejs caching and instead of using elements for each ajax call you can use `EtoolsAjaxRequestBehavior` (`sendRequest` method).

**Pull request closed without merging**
